import Layout from "@components/Layouts/Layout";
import InOutTransitionContainer from "@components/Layouts/TransitionContainer";
import Portfolio from "@components/WorkStore/Portfolio";
import { Work } from "@types";
import { AnimateSharedLayout, motion } from "framer-motion";
import type { NextPage } from "next";
import Head from "next/head";
import getWorks from "src/lib/mdxFiles";

interface WorkPageProps {
  works: Work[];
}
const WorkPage: NextPage<WorkPageProps> = ({ works }) => {
  console.log(works);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <InOutTransitionContainer>
          <Portfolio works={works} />
        </InOutTransitionContainer>
      </Layout>
    </>
  );
};
export const getStaticProps = () => {
  const works = getWorks();

  return {
    props: {
      works,
    },
  };
};

export default WorkPage;
