import Layout from "@components/Layouts/Layout";
import InOutTransitionContainer from "@components/Layouts/TransitionContainer";
import Portfolio from "@components/WorkStore/Portfolio";
import { AnimateSharedLayout, motion } from "framer-motion";
import type { NextPage } from "next";
import Head from "next/head";

const WorkPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <InOutTransitionContainer>
          <Portfolio />
        </InOutTransitionContainer>
      </Layout>
    </>
  );
};

export default WorkPage;
