import "../styles/globals.css";
import type { AppProps } from "next/app";
import GlobalStyles from "../styles/GlobalStyles";
import { AnimatePresence } from "framer-motion";
import Layout from "../src/components/Layouts/Layout";
import Head from "next/head";

function MyApp({ Component, pageProps, router }: AppProps) {
  const AnyComponent = Component as any;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdn.jsdelivr.net/gh/moonspam/NanumSquare@1.0/nanumsquare.css"
        ></link>
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        ></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@500&display=swap"
          rel="stylesheet"
        ></link>

        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        ></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Gothic+A1:wght@500&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <GlobalStyles />
      <AnimatePresence exitBeforeEnter>
        <AnyComponent key={router.route} {...pageProps} />
      </AnimatePresence>
    </>
  );
}

export default MyApp;
