import useDarkBgContext from "@components/DarkBgProvider/useDarkBgContext";
import HistoryGraph from "@components/HistoryGraph/HistoryGraph";
import Introduction from "@components/Introduction";
import Layout from "@components/Layouts/Layout";
import InOutTransitionContainer from "@components/Layouts/TransitionContainer";
import People from "@components/People";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";

const AboutPage: NextPage = () => {
  const { setIsBgBlack } = useDarkBgContext();
  useEffect(() => {
    setIsBgBlack(true);
    document.body.style.backgroundColor = "black";
    return () => {
      setIsBgBlack(false);
      document.body.style.backgroundColor = "white";
    };
  });

  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout isWhiteLogo={true} stickyHeaderOption={{}}>
        <InOutTransitionContainer>
          <div tw="bg-black">
            <Introduction />
            <People />
            <HistoryGraph />
          </div>
        </InOutTransitionContainer>
      </Layout>
    </>
  );
};

export default AboutPage;
