import HistoryGraph from "@components/HistoryGraph/HistoryGraph";
import Introduction from "@components/Introduction";
import Layout from "@components/Layouts/Layout";
import InOutTransitionContainer from "@components/Layouts/TransitionContainer";
import People from "@components/People";
import { motion, Variants } from "framer-motion";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import tw from "twin.macro";
import Header from "../src/components/Layouts/Header/Header";

const AboutPage: NextPage = () => {
  useEffect(() => {
    console.log(window);
    window.scrollTo(0, 0);
  }, []);
  useEffect(() => {
    document.body.style.backgroundColor = "black";
    return () => {
      document.body.style.backgroundColor = "white";
    };
  });
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout isWhiteLogo={true} stickyHeaderOption={{}}>
        <InOutTransitionContainer>
          <div tw="bg-black">
            <Introduction />
            <People />
            <HistoryGraph />
            <div tw="inline-flex h-16 w-full flex-nowrap overflow-x[scroll]">
              <div tw="bg-blue-400 flex[0 0 auto] w-1/2"></div>
              <div tw="flex[0 0 auto] w-1/2  bg-yellow-100"></div>
              <div tw="flex[0 0 auto] w-1/2  bg-purple-300"></div>
              <div tw="flex[0 0 auto] w-1/2  bg-green-300"></div>
            </div>
          </div>
        </InOutTransitionContainer>
      </Layout>
    </>
  );
};

export default AboutPage;
