import HistoryGraph from "@components/HistoryGraph/HistoryGraph";
import Introduction from "@components/Introduction";
import Layout from "@components/Layouts/Layout";
import InOutTransitionContainer from "@components/Layouts/TransitionContainer";
import People from "@components/People";
import { motion, Variants } from "framer-motion";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import tw from "twin.macro";
import Header from "../src/components/Layouts/Header/Header";

const AboutPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <InOutTransitionContainer>
          <Introduction />
          <People />
          <HistoryGraph />
        </InOutTransitionContainer>
      </Layout>
    </>
  );
};

export default AboutPage;
