import useDarkBgContext from "@components/contexts/DarkBgContext/useDarkBgContext";
import Layout from "@components/Layouts/Layout";
import InOutTransitionContainer from "@components/Layouts/TransitionContainer";
import { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import { Container } from "styles/globalStyleComponent";
import tw from "twin.macro";
const ContactPage: NextPage = () => {
  const { setIsBgBlack } = useDarkBgContext();
  useEffect(() => {
    setIsBgBlack(true);
    document.body.style.backgroundColor = "black";
    return () => {
      setIsBgBlack(false);
      document.body.style.backgroundColor = "white";
    };
  });

  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout isWhiteLogo={true} stickyHeaderOption={{}}>
        <InOutTransitionContainer>
          <Container>
            <div tw="bg-black  text-white max-w-content px-content mx-auto">
              <h1>Contact</h1>
            </div>
          </Container>
        </InOutTransitionContainer>
      </Layout>
    </>
  );
};

export default ContactPage;
