import HomeSlider from "@components/HomeSlider/HomeSlider";
import Layout from "@components/Layouts/Layout";
import InOutTransitionContainer from "@components/Layouts/TransitionContainer";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <InOutTransitionContainer>
          <HomeSlider />
          <div>
            <section className="w-full h-screen   text-white"></section>
          </div>
        </InOutTransitionContainer>
      </Layout>
    </>
  );
};

export default Home;
