import Layout from "@components/Layouts/Layout";
import InOutTransitionContainer from "@components/Layouts/TransitionContainer";
import type { NextPage } from "next";
import Head from "next/head";
import tw from "twin.macro";
import WorksList from "@components/Workslist";
import ImageSlider from "@components/HomeImageSlider";
import useDarkBgContext from "@components/contexts/DarkBgContext/useDarkBgContext";
import { useEffect } from "react";
import sliderMediaInfo from "@components/HomeImageSlider/sliderMediaInfo";
import { DarkBgProvider } from "@components/contexts/DarkBgContext/DarkBgProvider";
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Antller</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout stickyHeaderOption={{ stickyHeaderThreshold: 1400 }}>
        <InOutTransitionContainer>
          <ImageSlider />
          <WorksList />
        </InOutTransitionContainer>
      </Layout>
    </>
  );
};

export default Home;
