import HomeSlider from "@components/HomeSlider/HomeSlider";
import Layout from "@components/Layouts/Layout";
import InOutTransitionContainer from "@components/Layouts/TransitionContainer";
import type { NextPage } from "next";
import Head from "next/head";
import tw from "twin.macro";
import WorksList from "@components/Workslist";
import ImageSlider from "@components/HomeImageSlider";
import useDarkBgContext from "@components/contexts/DarkBgContext/useDarkBgContext";
import { useEffect } from "react";
const Home: NextPage = () => {
  const { setIsBgBlack } = useDarkBgContext();
  useEffect(() => {
    return () => {
      setIsBgBlack(false);
    };
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout stickyHeaderOption={{ stickyHeaderThreshold: 1400 }}>
        <InOutTransitionContainer>
          {/* <HomeSlider /> */}
          {/* <ImageSlider /> */}
          <ImageSlider />
          <WorksList />
        </InOutTransitionContainer>
      </Layout>
    </>
  );
};

export default Home;
