import { AnimateSharedLayout, motion } from "framer-motion";
import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/Layouts/Header";
import Layout from "../components/Layouts/Layout";
import TransitionContainer from "../components/Layouts/TransitionContainer";
import Portfolio from "../components/WorkStore/Portfolio";

const WorkPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <TransitionContainer>
          <Portfolio />
        </TransitionContainer>
      </Layout>
    </>
  );
};

export default WorkPage;
